apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: globals
spec:
  replicas: 1
  image: rabbitmq:3.13-management

  rabbitmq:
    additionalPlugins:
      - rabbitmq_management

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi