apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: questmaster-update-paths
  namespace: globals
spec:
  name: questmaster-update-paths
  vhost: /
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq