apiVersion: v1
kind: Service
metadata:
  name: permissions-mongo
  namespace: questmaster
spec:
  clusterIP: None
  selector:
    app: permissions-mongo
  ports:
    - port: 27017
      targetPort: 27017