apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: permissions-mongo
  namespace: questmaster
spec:
  serviceName: permissions-mongo
  replicas: 1

  selector:
    matchLabels:
      app: permissions-mongo

  template:
    metadata:
      labels:
        app: permissions-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongodb
            - name: MONGO_INITDB_DATABASE
              value: perm
          volumeMounts:
            - name: mongo-data
              mountPath: /var/lib/mongodb/data

  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi