version: "3.9"
services:
  postgres:
    container_name: keycloak-db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - authenticatordb
      - pgadmin
    ports:
      - "5432:5432"
      
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - authenticator
      - authenticatordb

networks:
  authenticator:
    name: authenticator
    driver: bridge
  authenticatordb:
    name: authenticatordb
    driver: bridge
  pgadmin:
    name: pgadmin
    external: true
  rabbitmq:
    name: rabbitmq
    external: true

volumes:
  postgres_data: