version: "3.9"
services:
  postgres:
    container_name: keycloak-db
    image: "postgres:16"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - auth_db
    ports:
      - "5432:5432"
      
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - auth
      - auth_db

  tunnel-auth:
    image: node:lts-alpine
    container_name: tunnel-auth
    command: npx localtunnel --port 8080 --local-host keycloak --subdomain auth-liminallabs
    networks:
      - auth
    depends_on:
      - keycloak

networks:
  auth:
    name: auth
    driver: bridge
  auth_db:
    name: auth_db
    driver: bridge

volumes:
  postgres_data: