version: "3.9"
services:
  postgres-core:
    container_name: rpgtracker-core-db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_core_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpgtracker-core
      POSTGRES_HOST: postgres-core
    networks:
      - rpgtrackerdb
      - pgadmin
    ports:
      - "5433:5432"
  
  postgres-coc:
    container_name: rpgtracker-coc-db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_coc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpgtracker-coc
      POSTGRES_HOST: postgres-coc
    networks:
      - rpgtrackerdb
      - pgadmin
    ports:
      - "5434:5432"

  rpgtracker-gateway:
    container_name: rpgtracker-gateway
    image: hannabananna/commons/gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev
      HBSITES_GATEWAY_FRONTEND_URL: http://localhost:3000
      HBSITES_GATEWAY_KEYCLOAK_BASE_URL: http://keycloak:8080
      HBSITES_GATEWAY_KEYCLOAK_CLIENT_ID: rpgtracker
      HBSITES_GATEWAY_KEYCLOAK_CLIENT_SECRET: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw
      HBSITES_GATEWAY_KEYCLOAK_REALM: HBsites
      HBSITES_GATEWAY_SESSION_COOKIE_NAME: rpgtracker_session
      HBSITES_GATEWAY_OAUTH_CALLBACK_URL: http://localhost:8081/oauth/callback
      HBSITES_GATEWAY_KEYCLOAK_REDIRECT_URL: http://localhost:8083

    ports: 
      - "8081:8080"
    networks:
      - rpgtracker
      - authenticator

  rpgtracker-core:
    container_name: rpgtracker-core
    image: hannabananna/rpgtracker/rpgtracker-core:latest
    depends_on:
      - postgres-core
    environment:
      JAVA_OPTS_APPEND: -Dquarkus.profile=docker-dev
    ports: 
      - "8080:8080"
    networks:
      - authenticator
      - rpgtracker
      - rpgtrackerdb

  # rpgtracker-core:
  #   container_name: rpgtracker-core
  #   image: hannabananna/rpgtracker/core:dev
  #   depends_on:
  #     - postgres-core
  #     - consul-rpgtracker
  #   ports: 
  #     - "8081:8081"
  #   networks:
  #     - rpgtracker
  #     - rpgtrackerdb
  #     - rabbitmq
  #     - authenticator

  # rpgtracker-coc:
  #   container_name: rpgtracker-coc
  #   image: rpgtracker/coc:latest
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker-dev
  #   depends_on:
  #     - postgres-coc
  #   ports: 
  #     - "8082:8082"
  #   networks:
  #     - rpgtracker
  #     - rpgtrackerdb
  #     - rabbitmq
  #     - authenticator
  
  consul:
    container_name: consul-rpgtracker
    image: hashicorp/consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - "8500:8500"
    networks:
      - rpgtracker

networks:
  rpgtrackerdb:
    name: rpgtrackerdb
    driver: bridge
  rpgtracker:
    name: rpgtracker
    driver: bridge
  pgadmin:
    name: pgadmin
    external: true
  rabbitmq:
    name: rabbitmq
    external: true
  authenticator:
    name: authenticator
    external: true

volumes:
  postgres_core_data:
  postgres_coc_data: