version: "3.9"
services:
  postgres-core:
    container_name: questmaster-core-db
    image: "postgres:16"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_core_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questmaster-core
      POSTGRES_HOST: postgres-core
    networks:
      - questmaster_db
    ports:
      - "5433:5432"

  gateway-db:
    container_name: questmaster-gateway-db
    image: mongo:8.2.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: gateway
    ports:
      - "27018:27017"
    volumes:
      - mongo_gateway_data:/data/db
    networks:
      - questmaster_db

  perm-db:
    container_name: questmaster-perm-db
    image: mongo:8.2.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: perm
    ports:
      - "27019:27017"
    volumes:
      - mongo_perm_data:/data/db
    networks:
      - questmaster_db

  questmaster-gateway:
    container_name: questmaster-gateway
    image: labs.liminal/gateway:1.0.0
    environment:
      ALLOWED_ORIGIN: https://questmaster-liminallabs.loca.lt,http://questmaster-liminallabs.loca.lt

      MANAGEMENT_ENDPOINT_GATEWAY_ACCESS: UNRESTRICTED
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

      SPRING_DATA_MONGODB_HOST: gateway-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: mongodb
      SPRING_DATA_MONGODB_DATABASE: gateway

      LIMINALLABS_GATEWAY_SESSION_COOKIE_NAME: QUESTMASTER_SESSION
      LIMINALLABS_GATEWAY_OAUTH_CALLBACK_URL: https://questmaster-gateway-liminallabs.loca.lt/oauth/callback
      LIMINALLABS_GATEWAY_FRONTEND_URL: https://questmaster-liminallabs.loca.lt
      LIMINALLABS_GATEWAY_COOKIE_DOMAIN: loca.lt
      LIMINALLABS_GATEWAY_COOKIE_SAME_SITE: Strict
      LIMINALLABS_GATEWAY_COOKIE_SECURE: false
      LIMINALLABS_GATEWAY_COOKIE_MAX_AGE: 3600

      LIMINALLABS_GATEWAY_AUTH_PROVIDER_NAME: keycloak
      LIMINALLABS_GATEWAY_AUTH_KEYCLOAK_BASE_URL: https://auth-liminallabs.loca.lt
      LIMINALLABS_GATEWAY_AUTH_KEYCLOAK_BASE_URL_INTERNAL: http://keycloak:8080
      LIMINALLABS_GATEWAY_AUTH_KEYCLOAK_REALM: LiminalLabs
      LIMINALLABS_GATEWAY_AUTH_KEYCLOAK_CLIENT_ID: questmaster
      LIMINALLABS_GATEWAY_AUTH_KEYCLOAK_CLIENT_SECRET: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw

      JAVA_TOOL_OPTIONS: -Dspring.config.additional-location=/config/routes.yml
    volumes:
      - ../../../gateway/config/questmaster-routes.yml:/config/routes.yml
    depends_on:
      - gateway-db
    ports: 
      - "8081:8080"
    networks:
      - questmaster
      - auth
      - questmaster_db

  questmaster-core:
    container_name: questmaster-core
    image: labs.liminal/questmaster/questmaster-core:1.0.0
    environment:
      OIDC_HOST: http://keycloak:8080/realms/LiminalLabs

      DB_URL: postgres://postgres:postgres@postgres-core:5432/questmaster-core

      MONGODB_URL: mongodb://root:mongodb@perm-db:27017/admin
      MONGODB_DATABASENAME: questmaster-perm
    depends_on:
      - postgres-core
    ports: 
      - "8082:8080"
    networks:
      - auth
      - rabbitmq
      - questmaster
      - questmaster_db

  questmaster-frontend:
    image: labs.liminal/questmaster/questmaster-frontend:1.0.0
    container_name: questmaster-frontend
    ports:
      - "3000:3000"
    
    # Variáveis de Runtime (Lado do Servidor)
    environment:
      CORE_API_URL: https://questmaster-gateway-liminallabs.loca.lt
      SESSION_COOKIE_NAME: QUESTMASTER_SESSION
    networks:
      - questmaster

      
  tunnel-frontend:
    image: node:lts-alpine
    container_name: tunnel-frontend
    # O comando aponta para o nome do serviço e a porta interna
    command: npx localtunnel --port 3000 --local-host questmaster-frontend --subdomain questmaster-liminallabs
    networks:
      - questmaster
    depends_on:
      - questmaster-frontend

  tunnel-gateway:
    image: node:lts-alpine
    container_name: tunnel-gateway
    command: npx localtunnel --port 8080 --local-host questmaster-gateway --subdomain questmaster-gateway-liminallabs
    networks:
      - questmaster
    depends_on:
      - questmaster-gateway

networks:
  questmaster_db:
    name: questmaster_db
    driver: bridge
  questmaster:
    name: questmaster
    driver: bridge
  rabbitmq:
    name: rabbitmq
    external: true
  auth:
    name: auth
    external: true

volumes:
  postgres_core_data:
  mongo_gateway_data:
  mongo_perm_data: