version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.13-management"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:9.11"
    environment:
      PGADMIN_DEFAULT_EMAIL: hannanicollew@outlook.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    tty: true
    healthcheck:
      test: ["CMD", "ping localhost:80 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5050:80"
    networks:
      - auth_db
      - questmaster_db
  
  aws-local:
    container_name: aws-local
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=-0
    volumes:
      - aws-data:/var/lib/localstack
    networks:
      - aws-local

  vault:
    image: hashicorp/vault:1.15.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"   # token para teste
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: server -dev -dev-root-token-id=root
    volumes:
      - vault-data:/var/lib/hashicorp/vault
    networks:
      - vault
      - questmaster_db

networks:
  rabbitmq:
    name: rabbitmq
    driver: bridge
  aws-local:
    name: aws
    driver: bridge
  vault:
    name: vault
    driver: bridge
  auth_db:
    name: auth_db
    external: true
  questmaster_db:
    name: questmaster_db
    external: true

volumes:
  aws-data:
  rabbitmq-data:
  vault-data: