version: "3.9"
services:
  postgres-core:
    container_name: rpgtracker-core-db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_core_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpgtracker-core
      POSTGRES_HOST: postgres-core
    networks:
      - rpgtrackerdb
      - pgadmin
    ports:
      - "5433:5432"

  postgres-gb:
    container_name: rpgtracker-gb-db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_gb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpgtracker-gb
      POSTGRES_HOST: postgres-gb
    networks:
      - rpgtrackerdb
      - pgadmin
    ports:
      - "5434:5432"

  gateway-db:
    container_name: rpgtracker-gateway-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: gateway
    ports:
      - "27018:27017"
    volumes:
      - mongo_gateway_data:/data/db
    networks:
      - rpgtrackerdb

  rpgtracker-gateway:
    container_name: rpgtracker-gateway
    image: hannabananna/commons/gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev
      HBSITES_GATEWAY_FRONTEND_URL: http://localhost:3000
      HBSITES_GATEWAY_KEYCLOAK_BASE_URL: http://keycloak:8080
      HBSITES_GATEWAY_KEYCLOAK_CLIENT_ID: rpgtracker
      HBSITES_GATEWAY_KEYCLOAK_CLIENT_SECRET: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw
      HBSITES_GATEWAY_KEYCLOAK_REALM: HBsites
      HBSITES_GATEWAY_SESSION_COOKIE_NAME: RPGTRACKER_SESSION
      HBSITES_GATEWAY_OAUTH_CALLBACK_URL: http://localhost:8081/oauth/callback
      HBSITES_GATEWAY_AMQP_QUEUE: rpgtracker-update-paths

    ports: 
      - "8081:8080"
    networks:
      - rpgtracker
      - authenticator
      - rabbitmq
      - rpgtrackerdb

  rpgtracker-core:
    container_name: rpgtracker-core
    image: hannabananna/rpgtracker/rpgtracker-core:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/HBsites
      QUARKUS_OIDC_CREDENTIALS_SECRET: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-core:5432/rpgtracker-core?currentSchema=public
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres-core:5432/rpgtracker-core?currentSchema=public
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      HBSITES_GATEWAY_URI: http://rpgtracker-core:8080
    ports: 
      - "8082:8080"
    networks:
      - authenticator
      - rabbitmq
      - rpgtracker
      - rpgtrackerdb

  rpgtracker-gb:
    container_name: rpgtracker-gb
    image: hannabananna/rpgtracker/rpgtracker-gb:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/HBsites
      QUARKUS_OIDC_CREDENTIALS_SECRET: xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-gb:5432/rpgtracker-gb?currentSchema=public
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres-gb:5432/rpgtracker-gb?currentSchema=public
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      HBSITES_GATEWAY_URI: http://rpgtracker-gb:8080
    ports: 
      - "8083:8080"
    networks:
      - authenticator
      - rabbitmq
      - rpgtracker
      - rpgtrackerdb

networks:
  rpgtrackerdb:
    name: rpgtrackerdb
    driver: bridge
  rpgtracker:
    name: rpgtracker
    driver: bridge
  pgadmin:
    name: pgadmin
    external: true
  rabbitmq:
    name: rabbitmq
    external: true
  authenticator:
    name: authenticator
    external: true

volumes:
  postgres_core_data:
  postgres_coc_data:
  postgres_gb_data:
  mongo_gateway_data: