apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: questmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: labs.liminal/gateway:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS__ALL__ALLOWEDORIGINS
              value: "http://localhost:3000"
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS__ALL__ALLOWEDMETHODS
              value: "*"
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS__ALL__ALLOWEDHEADERS
              value: "*"
            - name: SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATIONS__ALL__ALLOWCREDENTIALS
              value: "true"
            - name: MANAGEMENT_ENDPOINT_GATEWAY_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq.globals.svc.cluster.local"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: questmaster-gateway-user-credentials
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: questmaster-gateway-user-credentials
                  key: password
            - name: SPRING_DATA_MONGODB_HOST
              value: "gateway-mongo"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "root"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "gateway"
            - name: LIMINALLABS_GATEWAY_SESSION_COOKIE_NAME
              value: "QUESTMASTER_SESSION"
            - name: LIMINALLABS_GATEWAY_OAUTH_CALLBACK_URL
              value: "http://questmaster.localhost/oauth/callback"
            - name: LIMINALLABS_GATEWAY_FRONTEND_URL
              value: "http://localhost:3000"
            - name: LIMINALLABS_GATEWAY_KEYCLOAK_BASE_URL
              value: "http://codex.localhost"
            - name: LIMINALLABS_GATEWAY_KEYCLOAK_BASE_URL_INTERNAL
              value: "http://keycloak.auth.svc.cluster.local:8080"
            - name: LIMINALLABS_GATEWAY_KEYCLOAK_REALM
              value: "LiminalLabs"
            - name: LIMINALLABS_GATEWAY_KEYCLOAK_CLIENT_ID
              value: "questmaster"
            - name: LIMINALLABS_GATEWAY_KEYCLOAK_CLIENT_SECRET
              value: "xKa7P5CGXwoYnSjQrI7g9UUXYP16LXOw"
            - name: LIMINALLABS_GATEWAY_AMQP_QUEUE
              value: "questmaster-update-paths"